# Worksheet 04

Name:  Beaudlaire Jeancharles
UID: U70445938

### Topics

- Distance & Similarity

### Distance & Similarity

#### Part 1

a) In the minkowski distance, describe what the parameters p and d are.

In the Minkowski distance the parameter P represents the order of the Minkowski distance.
it determines  how the Minkowski distance is being calculated. And, the d represents the dimenssional space where the data points exist.

b) In your own words describe the difference between the Euclidean distance and the Manhattan distance.

The key difference between Euclidean Distance and Manhattan Distance lies in how they compute distance: Euclidean Distance calculates the shortest possible path(Straight Line) between two points, while Manhattan Distance calculates the distance along the grid lines.





Consider A = (0, 0) and B = (1, 1). When:

- p = 1, d(A, B) = 2
- p = 2, d(A, B) = $\sqrt{2} = 1.41$
- p = 3, d(A, B) = $2^{1/3} = 1.26$
- p = 4, d(A, B) = $2^{1/4} = 1.19$

c) Describe what you think distance would look like when p is very large.

As p is approaching infinity, the Minkowski Distance behaves more like the Chebyshev Distance because the contribution of each coordinates difference to the overall distance calculation becomes increasingly weigghted towards the largest difference.

d) Is the minkowski distance still a distance function when p < 1? Expain why / why not.

When p < 1, the Minkowski Distance is not a distance because it violates the Triangle Inequality. So, it can lead to inconsistencies in measuring distances. However, 

e) when would you use cosine similarity over the euclidan distance?

We should use Cosine (dis)similarity  over Euclidean distance when Direction matters more than magnitude. 

f) what does the jaccard distance account for that the manhattan distance doesn't?
The thing that the Jaccard Distance accounts for that the Manhattan Distance does not is: 
it accounts for the presence of or absence of elements in sets but does not consider the magnitude or quantitative differences between elements.

#### Part 2

Consider the following two sentences:

In [117]:
s1 = "hello my name is Alice"  
s2 = "hello my name is Bob"

using the union of words from both sentences, we can represent each sentence as a vector. Each element of the vector represents the presence or absence of the word at that index.

In this example, the union of words is ("hello", "my", "name", "is", "Alice", "Bob") so we can represent the above sentences as such:

In [118]:
v1 = [1,    1, 1,   1, 1,    0]
#     hello my name is Alice
v2 = [1,    1, 1,   1, 0, 1]
#     hello my name is    Bob

Programmatically, we can do the following:

In [119]:
corpus = [s1, s2]
#print(corpus)
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)
v1 = [1 if x in s1 else 0 for x in all_words]
print(v1)

['hello', 'name', 'is', 'my', 'Alice', 'Bob']
[1, 1, 1, 1, 1, 0]


Let's add a new sentence to our corpus:

In [120]:
s3 = "hi my name is Claude"
corpus.append(s3)
print(corpus)

['hello my name is Alice', 'hello my name is Bob', 'hi my name is Claude']


a) What is the new union of words used to represent s1, s2, and s3?

In [121]:
all_words = list(set([item for x in corpus for item in x.split()]))
print(all_words)

['hi', 'hello', 'name', 'is', 'my', 'Alice', 'Bob', 'Claude']


b) Represent s1, s2, and s3 as vectors as above, using this new set of words.

In [122]:
def sentence_to_vector(sentence, all_words):
    vector = [0] * len(all_words)
    #print(vector)
    words = sentence.split()
    for word in words:
        if word in all_words:
            vector[all_words.index(word)] += 1
    return vector

v1 = sentence_to_vector(s1, all_words)
v2 = sentence_to_vector(s2, all_words)
v3 = sentence_to_vector(s3, all_words)

print(v1)
print(v2)
print(v3)
    

[0, 1, 1, 1, 1, 1, 0, 0]
[0, 1, 1, 1, 1, 0, 1, 0]
[1, 0, 1, 1, 1, 0, 0, 1]


c) Write a function that computes the manhattan distance between two vectors. Which pair of vectors are the most similar under that distance function?

In [123]:
def manhattan_dist(vect1,vect2):
    if len(vect1) != len(vect2):
        raise RuntimeError("x and and y should be same dimension!!!")
    return sum(abs(x - y) for x,y in zip(vect1, vect2))
dist_v1_v2 = manhattan_dist(v1,v2)
dist_v1_v3 = manhattan_dist(v1,v3)
dist_v2_v3 = manhattan_dist(v2,v3)

print(dist_v1_v2)
print(dist_v1_v2)
print(dist_v2_v3)
    
    

2
2
4


d) Create a matrix of all these vectors (row major) and add the following sentences in vector form:

- "hi Alice"
- "hello Claude"
- "Bob my name is Claude"
- "hi Claude my name is Alice"
- "hello Bob"

In [124]:
# Define the vectors
s1 = [1, 0, 1, 0, 1, 0, 1, 1]
s2 = [1, 0, 1, 0, 1, 1, 0, 1]
s3 = [1, 1, 0, 1, 1, 0, 0, 1]

# Define the new sentences
new_sentences = [
    "hi Alice",
    "hello Claude",
    "Bob my name is Claude",
    "hi Claude my name is Alice",
    "hello Bob"
]

# Function to convert sentence to vector
def sentence_to_vector(sentence, all_words):
    vector = [0] * len(all_words)
    words = sentence.split()
    for word in words:
        if word in all_words:
            vector[all_words.index(word)] += 1
    return vector

# Convert new sentences to vectors
new_sentence_vectors = [sentence_to_vector(sentence, all_words) for sentence in new_sentences]

# Create the matrix
matrix = [s1, s2, s3] + new_sentence_vectors

# Display the matrix
for row in matrix:
    print(row)


[1, 0, 1, 0, 1, 0, 1, 1]
[1, 0, 1, 0, 1, 1, 0, 1]
[1, 1, 0, 1, 1, 0, 0, 1]
[1, 0, 0, 0, 0, 1, 0, 0]
[0, 1, 0, 0, 0, 0, 0, 1]
[0, 0, 1, 1, 1, 0, 1, 1]
[1, 0, 1, 1, 1, 1, 0, 1]
[0, 1, 0, 0, 0, 0, 1, 0]


e) How many rows and columns does this matrix have?

In [125]:
num_rows = len(matrix)
num_cols = len(matrix[0])

print("The number of rows is: ", num_rows)
print("The number of columns is: ", num_cols)

The number of rows is:  8
The number of columns is:  8


f) When using the Manhattan distance, which two sentences are the most similar?

In [116]:
# Initialize variables to store information about the most similar pair
def minkowski(list1,list2, a):
    s1 = "hi Alice"
    s2 = "hello Claude"
    s3 = "Bob my name is Claude"
    s4 = "hi Claude my name is Alice"
    s5 = "hello Bob"

   
    corpus[s1,s2,s3,s4,s5]

    all_words = list(set([item for x in corpus for item in x.split()]))
    print(all_words)

    v1 = [1 if x in s1 else 0 for x in all_words]
    print(v1)
    v2 = [1 if x in s2 else 0 for x in all_words]
    print(v2)
    v3 = [1 if x in s3 else 0 for x in all_words]
    print(v3)
    v4 = [1 if x in s4 else 0 for x in all_words]
    print(v4)
    v5 = [1 if x in s5 else 0 for x in all_words]
    print(v5)

    listv = [v1,v2,v3,v4,v5]
    lowest = float('inf')
    for x in range(len(listv)):
        for y in range(len(listv)):
            if x != y:
                temp = minkowski(listv[x], listv[y], 1)
                if temp< lowest:
                    result = [x+1, y+1]
    print(result) 

#### Part 3 Challenge

Given a set of graphs $\mathcal{G}$, each graph $G \in \mathcal{G}$ is defined over the same set of nodes $V$. The graphs are represented by their adjacency matrices, which are 2D arrays where each element indicates whether a pair of nodes is connected by an edge.

Your task is to compute the pairwise distances between these graphs based on a specific distance metric. The distance $d(G, G')$ between two graphs $G = (V, E)$ and $G' = (V, E')$ is defined as the sum of the number of edges in $G$ but not in $G'$, and the number of edges in $G'$ but not in $G$. Mathematically, this can be expressed as:

$$
d(G, G') = |E \setminus E'| + |E' \setminus E|.
$$

##### Requirements:
1. **Input**: Should take a list of 2D numpy arrays as input. Each array represents the adjacency matrix of a graph.

2. **Output**: Should output a pairwise distance matrix. If there are $n$ graphs in the input list, the output should be an $n \times n$ matrix where the entry at position $(i, j)$ represents the distance between the $i^{th}$ and $j^{th}$ graph.


In [104]:
import numpy as np

def graph_pairwise_dist(graphs):
    length = len(graphs)
    dist = np.zeros((length,length), dtype=int)
    
    for i in range(length):
        for j in range(i+1, length):
            graph1 = graphs[i]
            graph2 = graphs[j]
            edges_graph1 = set(zip(*np.where(graph1==1)))
            edges_graph2 = set(zip(*np.where(graph1==1)))
            
            distance = len(edges_graph1 - edges_graph2) + len(edges_graph2 - edges_graph1)
            dist[i][j] = distance
            dist[j][i] = distance
            
    return dist
        
graph1 = np.array([[0, 1, 1],[1, 0, 0],[1, 0, 0]])
graph2 = np.array([[0, 1, 0],[1, 0, 1],[0, 1, 0]])
graph3 = np.array([[0, 1, 1],[1, 0, 1],[1, 1, 0]])
        
graphs = [graph1, graph2, graph3]
dist = graph_pairwise_dist(graphs)
        
print(dist)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
